services:

  xserver:
    image: iocchi/xserver
    container_name: xserver
    ipc: host
    security_opt:
      - seccomp:unconfined
    environment:
      - DISPLAY=:9
    hostname: xserver
    ports:
      - 3000:80  # web vnc viewer
      - 3001:81  # experimental     
      - 5900:5900  # websockify
    volumes:
      - $PWD/fluxbox:/opt/fluxbox
      - $PWD/fluxbox/menu:/root/.fluxbox/menu
      - $PWD/fluxbox/keys:/root/.fluxbox/keys
      - $PWD/fluxbox/init:/root/.fluxbox/init
      - $PWD/fluxbox/apps:/root/.fluxbox/apps

  marrtino_gazebo:
    image: marrtino2:user
    container_name: marrtino2_gz
    runtime: runc
    dns: 8.8.8.8
    hostname: marrtino2
    ports:
      - 2222:2222  # ssh
      - 3080:3080  # web
      - 9876:9876  # websocket
      - 9890:9890  # ROS bridge websocket
    tty: true
    security_opt:
      - seccomp:unconfined
    environment:
      - DISPLAY=:9
      - GZ_SIM_RESOURCE_PATH=/home/robot/src/marrtino_gazebo/marrtino_gazebo/models
    volumes_from:
      - xserver
    depends_on:
      - xserver
    volumes:
      - $PWD/..:/home/robot/src/marrtino_gazebo
      - $PWD/nginx/default:/etc/nginx/sites-available/default
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf




