services:

  marrtino_gazebo:
    image: marrtino2:user
    container_name: marrtino_gazebo
    runtime: ${DOCKER_RUNTIME}
    cap_add:
      - NET_ADMIN
    sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
    env_file:
        - path: config.env
          required: true
    dns: 8.8.8.8
    tty: true
    hostname: marrtino_gazebo
    ports:
      - 2222:2222  # ssh
      - 3080:3080  # web
      - 9876:9876  # websocket code_server
      - 9877:9877  # websocket lsb_admin
      - 9890:9890  # ROS bridge websocket
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - GZ_SIM_RESOURCE_PATH=/home/robot/src/marrtino_gazebo/marrtino_gazebo/models
    volumes:
      - $PWD/..:/home/robot/src/marrtino_gazebo
      - $PWD/etc/nginx/default:/etc/nginx/sites-available/default
      - $PWD/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /dev/dri/:/dev/dri/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/robot/.Xauthority

    # network_mode: "host"



