services:

  marrtino_gazebo:
    image: marrtino2:gazebo
    container_name: marrtino2_gazebo
    runtime: ${DOCKER_RUNTIME}
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all    
    volumes:
      - /dev/dri/card0:/dev/dri/card0
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/robot/.Xauthority
      - $PWD/..:/home/robot/src/marrtino_gazebo


#      - $PWD:/home/robot/gazebo


# - GZ_SIM_RESOURCE_PATH=/home/robot/gazebo/models/
