# Docker file for MARRtino software
# ROS2 Humble/Iron/Jazzy
# System image

# docker build -t marrtino2:system -f Dockerfile.system .

# ros:iron-ros-base-jammy    22.04
# ros:jazzy-ros-base-noble   24.04

#FROM ros:humble-ros-base-jammy
#FROM ros:iron-ros-base-jammy
FROM ros:jazzy-ros-base-noble

ARG MARRTINO_SYSTEM_VERSION=5.0

ARG DEBIAN_FRONTEND=noninteractive

###### User root ######

# install libraries and ros packages 

# Remove ROS signatures (if ros:jazzy-ros-base-noble old)
#RUN rm -f /etc/apt/sources.list.d/ros2* && \
#    rm -f /usr/share/keyrings/ros* && \
#    rm -rf /var/lib/apt/lists/*

RUN apt update && \
    apt install -y --no-install-recommends \
        tmux less sudo eom nano curl \
        openssl shellinabox netcat-openbsd \
        wget iputils-ping net-tools openssh-client openssh-server \
        nginx wireguard libwebsockets-dev

    #apt clean && \
    #rm -rf /var/lib/apt/lists/*

ADD docker/etc/sshd_config /etc/ssh/sshd_config
ADD docker/etc/sudoers /etc/sudoers

RUN update-rc.d ssh defaults

RUN apt update && \
    apt install -y --no-install-recommends \
        python3 python3-pip python3-venv pipx \
        python3-requests python3-websockets

RUN cd /usr/bin && ln -s python3 python


WORKDIR /opt

CMD [ "/usr/bin/tmux" ]


