FROM marrtino2:system

# install gz and ros2-gz

USER root

RUN curl https://packages.osrfoundation.org/gazebo.gpg --output /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null

RUN apt update && \
    apt install -y --no-install-recommends gz-harmonic

RUN apt update && \
    apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-ros-gz ros-${ROS_DISTRO}-ros-gz-sim ros-${ROS_DISTRO}-gz-ros2-control \
        ros-${ROS_DISTRO}-gz-ros2-control-demos \
        ros-${ROS_DISTRO}-ros2-control ros-${ROS_DISTRO}-ros2-control-cmake \
        ros-${ROS_DISTRO}-ros2-controllers ros-${ROS_DISTRO}-controller-manager \
        ros-${ROS_DISTRO}-tf-transformations


#RUN apt clean && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

CMD [ "/usr/bin/tmux" ]




