# Docker file for MARRtino software
# ROS2 Humble/Iron/Jazzy
# User image

FROM marrtino2:gazebo

ARG MARRTINO_SYSTEM_VERSION=5.0

ARG MACHTYPE=default
ARG UID=1000
ARG GID=1000

ARG DEBIAN_FRONTEND=noninteractive

        
# robot user

USER root

# Create user: robot (password: robot) with sudo power

RUN useradd -ms /bin/bash robot && echo "robot:robot" | chpasswd && adduser robot sudo

RUN deluser ubuntu

RUN usermod -u $UID robot && groupmod -g $GID robot || true
RUN chown -R robot:robot /home/robot

RUN adduser robot audio
RUN adduser robot video
RUN adduser robot dialout
RUN adduser robot www-data

# User robot

USER robot

RUN echo "set -g mouse on" > $HOME/.tmux.conf 
RUN touch ~/.sudo_as_admin_successful


# ROS2 workspace

RUN  mkdir -p $HOME/ros2_ws/src && cd $HOME/ros2_ws


# Set up .bashrc

RUN echo "export MARRTINO_APPS_HOME=$HOME/src/marrtino_apps" >> $HOME/.bashrc

RUN echo "export MARRTINO_VERSION=\"docker\"" >> $HOME/.bashrc

RUN echo "docker $MARRTINO_SYSTEM_VERSION" >> $HOME/.marrtino_version

# RUN echo "export ROS_DOMAIN_ID=5" >> ~/.bashrc

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> $HOME/.bashrc






#########################
# marrtino_gazebo setup #
#########################

USER robot

ADD . /home/robot/src/marrtino_gazebo

RUN cd ~/ros2_ws/src && \
    ln -s ~/src/marrtino_gazebo/marrtino_gazebo . && \
    ln -s ~/src/marrtino_gazebo/marrtino_control .


RUN bash -ci "cd ~/ros2_ws && colcon build"

RUN bash -c "echo \"export PATH=${PATH}:/home/robot/.local/bin\" >> ~/.bashrc"
RUN bash -c "echo \"source ~/ros2_ws/install/setup.bash\" >> ~/.bashrc"


USER root

RUN apt update && \
    apt install -y --no-install-recommends \
        python3-websocket tcpdump

USER robot

RUN pip install  --break-system-packages openai chromadb

RUN pip install  --break-system-packages google-genai google-auth-oauthlib google-auth-httplib2 google-api-python-client

WORKDIR /home/robot

ENTRYPOINT sudo service ssh start && sudo service nginx start && tmux

