# Docker file for MARRtino software
# ROS2 Humble/Iron/Jazzy
# System image

# docker build -t marrtino2:system -f Dockerfile.system .

# ros:iron-ros-base-jammy    22.04
# ros:jazzy-ros-base-noble   24.04

#FROM ros:humble-ros-base-jammy
#FROM ros:iron-ros-base-jammy
FROM ros:jazzy-ros-base-noble

ARG MARRTINO_SYSTEM_VERSION=5.0

ARG DEBIAN_FRONTEND=noninteractive

###### User root ######

# install libraries and ros packages 

# Remove ROS signatures (if ros:jazzy-ros-base-noble old)
#RUN rm -f /etc/apt/sources.list.d/ros2* && \
#    rm -f /usr/share/keyrings/ros* && \
#    rm -rf /var/lib/apt/lists/*

RUN apt update && \
    apt install -y --no-install-recommends \
        tmux less sudo eom nano curl \
        openssl shellinabox netcat-openbsd \
        wget iputils-ping net-tools openssh-client nginx \
        libwebsockets-dev
        
    #apt clean && \
    #rm -rf /var/lib/apt/lists/*


# ROS packages

USER root

# Add new ROS signatures (if ros:jazzy-ros-base-noble old)
#RUN apt update && \
#    apt install -y software-properties-common && \
#    add-apt-repository universe

#RUN export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') && \
#    curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $UBUNTU_CODENAME)_all.deb" && \
#    apt install -y /tmp/ros2-apt-source.deb

RUN apt update && apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-turtlesim  ~nros-${ROS_DISTRO}-rqt*


WORKDIR /opt

CMD [ "/usr/bin/tmux" ]


